import type { Order } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2026-001",
    customerId: "c1",
    customerName: "ABC Corp",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "processing",
    channel: "direct",
    value: 5_500_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [
      {
        id: "a1",
        name: "passport_scan.pdf",
        type: "pdf",
        size: 245_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-02",
      },
      {
        id: "a2",
        name: "labor_contract.docx",
        type: "word",
        size: 88_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-02",
      },
    ],
    licenseAttachments: [],
    approvalStatus: "pending_review",
    pendingTransition: { toStage: "waiting_gov", requestId: "ar1" },
    approvalHistory: [
      {
        id: "ar0",
        fromStage: "new",
        toStage: "processing",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-01",
        note: "Docs collected",
        status: "approved",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-07-01",
      },
      {
        id: "ar1",
        fromStage: "processing",
        toStage: "waiting_gov",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-08",
        note: "Ready to submit to DOLAB",
        status: "pending",
      },
    ],
    needsVat: true,
    contractNumber: 1,
    deadline: "2026-08-20",
    vatIssueDeadline: "2026-08-15",

    createdAt: "2026-07-01",
    month: "2026-07",
  },
  {
    id: "o2",
    orderNumber: "ORD-2026-002",
    customerId: "c3",
    customerName: "Tech Startup JSC",
    serviceId: "s3",
    serviceName: "Business License",
    stage: "waiting_gov",
    channel: "ctv",
    ctvId: "ctv1",
    ctvName: "Hoang CTV",
    value: 7_000_000,
    ctvPrice: 8_800_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [
      {
        id: "a3",
        name: "company_docs.xlsx",
        type: "excel",
        size: 52_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-06",
      },
    ],
    approvalStatus: "none",
    approvalHistory: [
      {
        id: "ar2",
        fromStage: "processing",
        toStage: "waiting_gov",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-07",
        status: "approved",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-07-07",
      },
    ],
    needsVat: true,
    contractNumber: 2,
    deadline: "2026-09-01",
    vatIssueDeadline: "2026-08-25",
    licenseAttachments: [
      {
        id: "lic1",
        name: "business_license_final.pdf",
        type: "pdf",
        size: 120000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-20",
        issuedAt: "2026-07-15",
        expiresAt: "2026-10-15",
      },
    ],
    createdAt: "2026-07-05",
    month: "2026-07",
  },
  {
    id: "o3",
    orderNumber: "ORD-2026-003",
    customerId: "c4",
    customerName: "Tran Thi B",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "new",
    channel: "website",
    value: 3_200_000,
    assignedUserId: "u5",
    assignedUserName: "Vo Staff B",
    submitterId: "u5",
    submitterName: "Vo Staff B",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: false,
    deadline: "2026-08-10",

    createdAt: "2026-07-10",
    month: "2026-07",
  },
  {
    id: "o4",
    orderNumber: "ORD-2026-004",
    customerId: "c2",
    customerName: "Nguyen Van A",
    serviceId: "s4",
    serviceName: "TRC Application",
    stage: "completed",
    channel: "referral",
    value: 4_500_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u1",
    reviewerName: "Nguyen Director",
    attachments: [
      {
        id: "a4",
        name: "trc_result.pdf",
        type: "pdf",
        size: 310_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-06-28",
      },
    ],
    approvalStatus: "approved",
    approvalHistory: [
      {
        id: "ar3",
        fromStage: "waiting_gov",
        toStage: "completed",
        requestedBy: "Le Staff A",
        requestedAt: "2026-06-28",
        status: "approved",
        reviewedBy: "Nguyen Director",
        reviewedAt: "2026-06-29",
        reviewNote: "All docs verified",
      },
    ],
    needsVat: true,
    contractNumber: 3,
    deadline: "2026-07-30",
    vatIssueDeadline: "2026-07-28",
    licenseAttachments: [
      {
        id: "lic2",
        name: "work_permit_final.pdf",
        type: "pdf",
        size: 98000,
        uploadedBy: "Vo Staff B",
        uploadedAt: "2026-07-25",
        issuedAt: "2026-07-20",
        expiresAt: "2027-07-20",
      },
    ],
    createdAt: "2026-06-15",
    month: "2026-06",
  },
  {
    id: "o5",
    orderNumber: "ORD-2026-005",
    customerId: "c1",
    customerName: "ABC Corp",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "waiting_customer",
    channel: "ctv",
    ctvId: "ctv2",
    ctvName: "Linh Partner",
    value: 2_500_000,
    ctvPrice: 3_000_000,
    assignedUserId: "u5",
    assignedUserName: "Vo Staff B",
    submitterId: "u5",
    submitterName: "Vo Staff B",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "rejected",
    approvalHistory: [
      {
        id: "ar4",
        fromStage: "waiting_customer",
        toStage: "processing",
        requestedBy: "Vo Staff B",
        requestedAt: "2026-06-25",
        note: "Customer provided missing passport",
        status: "rejected",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-06-26",
        reviewNote: "Passport scan is blurry — re-upload",
      },
    ],
    needsVat: false,
    deadline: "2026-08-05",

    createdAt: "2026-06-20",
    month: "2026-06",
  },
  {
    id: "o6",
    orderNumber: "ORD-2026-006",
    customerId: "c3",
    customerName: "Tech Startup JSC",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "new",
    channel: "direct",
    value: 5_000_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "pending_review",
    pendingTransition: { toStage: "processing", requestId: "ar5" },
    approvalHistory: [
      {
        id: "ar5",
        fromStage: "new",
        toStage: "processing",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-21",
        note: "Kick off processing",
        status: "pending",
      },
    ],
    needsVat: true,
    contractNumber: 4,
    deadline: "2026-09-15",
    vatIssueDeadline: "2026-09-01",

    createdAt: "2026-07-20",
    month: "2026-07",
  },
  {
    id: "o7",
    orderNumber: "ORD-2026-007",
    customerId: "c5",
    customerName: "XYZ Trading",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "processing",
    channel: "direct",
    value: 5_000_000,
    assignedUserId: "u6",
    assignedUserName: "Do Staff C",
    submitterId: "u6",
    submitterName: "Do Staff C",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: false,

    createdAt: "2026-07-22",
    month: "2026-07",
  },
  {
    id: "o8",
    orderNumber: "ORD-2026-008",
    customerId: "c2",
    customerName: "Nguyen Van A",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "new",
    channel: "direct",
    value: 9_900_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: false,

    createdAt: "2026-08-01",
    month: "2026-08",
  },
  {
    id: "o9",
    orderNumber: "ORD-2026-009",
    customerId: "c5",
    customerName: "XYZ Trading",
    serviceId: "s3",
    serviceName: "Business License",
    stage: "waiting_customer",
    channel: "direct",
    value: 1_100_000,
    assignedUserId: "u11",
    assignedUserName: "Lan Sales",
    submitterId: "u11",
    submitterName: "Lan Sales",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: true,
    contractNumber: 5,
    vatIssueDeadline: "2026-08-30",

    createdAt: "2026-08-03",
    month: "2026-08",
  },
  {
    id: "o10",
    orderNumber: "ORD-2026-010",
    customerId: "c4",
    customerName: "Tran Thi B",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "waiting_gov",
    channel: "direct",
    value: 15_400_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u8",
    reviewerName: "Hoang Ops",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: false,

    createdAt: "2026-08-05",
    month: "2026-08",
  },
  {
    id: "o11",
    orderNumber: "ORD-2026-011",
    customerId: "c1",
    customerName: "ABC Corp",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "completed",
    channel: "direct",
    value: 6_600_000,
    assignedUserId: "u6",
    assignedUserName: "Do Staff C",
    submitterId: "u6",
    submitterName: "Do Staff C",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: true,
    contractNumber: 6,
    licenseAttachments: [
      {
        id: "lic3",
        name: "trc_final.pdf",
        type: "pdf",
        size: 110000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-06-01",
        issuedAt: "2026-05-20",
        expiresAt: "2026-09-20",
      },
    ],
    createdAt: "2026-06-15",
    month: "2026-06",
  },
  {
    id: "o12",
    orderNumber: "ORD-2026-012",
    customerId: "c3",
    customerName: "Tech Startup JSC",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "cancelled",
    channel: "direct",
    value: 4_400_000,
    assignedUserId: "u12",
    assignedUserName: "Hung QA",
    submitterId: "u12",
    submitterName: "Hung QA",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    licenseAttachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    needsVat: false,

    createdAt: "2026-07-28",
    month: "2026-07",
  },
];
