import type { Order } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2026-001",
    customerId: "c1",
    customerName: "ABC Corp",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "processing",
    channel: "direct",
    value: 5_500_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [
      {
        id: "a1",
        name: "passport_scan.pdf",
        type: "pdf",
        size: 245_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-02",
      },
      {
        id: "a2",
        name: "labor_contract.docx",
        type: "word",
        size: 88_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-02",
      },
    ],
    approvalStatus: "pending_review",
    pendingTransition: { toStage: "waiting_gov", requestId: "ar1" },
    approvalHistory: [
      {
        id: "ar0",
        fromStage: "new",
        toStage: "processing",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-01",
        note: "Docs collected",
        status: "approved",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-07-01",
      },
      {
        id: "ar1",
        fromStage: "processing",
        toStage: "waiting_gov",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-08",
        note: "Ready to submit to DOLAB",
        status: "pending",
      },
    ],
    createdAt: "2026-07-01",
    month: "2026-07",
  },
  {
    id: "o2",
    orderNumber: "ORD-2026-002",
    customerId: "c3",
    customerName: "Tech Startup JSC",
    serviceId: "s3",
    serviceName: "Business License",
    stage: "waiting_gov",
    channel: "ctv",
    ctvId: "ctv1",
    ctvName: "Hoang CTV",
    value: 7_000_000,
    ctvPrice: 8_800_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [
      {
        id: "a3",
        name: "company_docs.xlsx",
        type: "excel",
        size: 52_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-07-06",
      },
    ],
    approvalStatus: "none",
    approvalHistory: [
      {
        id: "ar2",
        fromStage: "processing",
        toStage: "waiting_gov",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-07",
        status: "approved",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-07-07",
      },
    ],
    createdAt: "2026-07-05",
    month: "2026-07",
  },
  {
    id: "o3",
    orderNumber: "ORD-2026-003",
    customerId: "c4",
    customerName: "Tran Thi B",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "new",
    channel: "website",
    value: 3_200_000,
    assignedUserId: "u5",
    assignedUserName: "Vo Staff B",
    submitterId: "u5",
    submitterName: "Vo Staff B",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    approvalStatus: "none",
    approvalHistory: [],
    createdAt: "2026-07-10",
    month: "2026-07",
  },
  {
    id: "o4",
    orderNumber: "ORD-2026-004",
    customerId: "c2",
    customerName: "Nguyen Van A",
    serviceId: "s4",
    serviceName: "TRC Application",
    stage: "completed",
    channel: "referral",
    value: 4_500_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u1",
    reviewerName: "Nguyen Director",
    attachments: [
      {
        id: "a4",
        name: "trc_result.pdf",
        type: "pdf",
        size: 310_000,
        uploadedBy: "Le Staff A",
        uploadedAt: "2026-06-28",
      },
    ],
    approvalStatus: "approved",
    approvalHistory: [
      {
        id: "ar3",
        fromStage: "waiting_gov",
        toStage: "completed",
        requestedBy: "Le Staff A",
        requestedAt: "2026-06-28",
        status: "approved",
        reviewedBy: "Nguyen Director",
        reviewedAt: "2026-06-29",
        reviewNote: "All docs verified",
      },
    ],
    createdAt: "2026-06-15",
    month: "2026-06",
  },
  {
    id: "o5",
    orderNumber: "ORD-2026-005",
    customerId: "c1",
    customerName: "ABC Corp",
    serviceId: "s2",
    serviceName: "Visa Processing",
    stage: "waiting_customer",
    channel: "ctv",
    ctvId: "ctv2",
    ctvName: "Linh Partner",
    value: 2_500_000,
    ctvPrice: 3_000_000,
    assignedUserId: "u5",
    assignedUserName: "Vo Staff B",
    submitterId: "u5",
    submitterName: "Vo Staff B",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    approvalStatus: "rejected",
    approvalHistory: [
      {
        id: "ar4",
        fromStage: "waiting_customer",
        toStage: "processing",
        requestedBy: "Vo Staff B",
        requestedAt: "2026-06-25",
        note: "Customer provided missing passport",
        status: "rejected",
        reviewedBy: "Tran Admin",
        reviewedAt: "2026-06-26",
        reviewNote: "Passport scan is blurry — re-upload",
      },
    ],
    createdAt: "2026-06-20",
    month: "2026-06",
  },
  {
    id: "o6",
    orderNumber: "ORD-2026-006",
    customerId: "c3",
    customerName: "Tech Startup JSC",
    serviceId: "s1",
    serviceName: "Work Permit",
    stage: "new",
    channel: "direct",
    value: 5_000_000,
    assignedUserId: "u3",
    assignedUserName: "Le Staff A",
    submitterId: "u3",
    submitterName: "Le Staff A",
    reviewerId: "u2",
    reviewerName: "Tran Admin",
    attachments: [],
    approvalStatus: "pending_review",
    pendingTransition: { toStage: "processing", requestId: "ar5" },
    approvalHistory: [
      {
        id: "ar5",
        fromStage: "new",
        toStage: "processing",
        requestedBy: "Le Staff A",
        requestedAt: "2026-07-21",
        note: "Kick off processing",
        status: "pending",
      },
    ],
    createdAt: "2026-07-20",
    month: "2026-07",
  },
];
