import type { Ctv } from "./types";

/** Hoa hồng = Giá CTV − giá niêm yết */
export const MOCK_CTVS: Ctv[] = [
  {
    id: "ctv1",
    name: "Hoang CTV",
    phone: "0909111222",
    email: "hoang.ctv@mail.com",
    status: "active",
    totalJobs: 2,
    totalCommission: 2_800_000,
    jobs: [
      {
        orderId: "o2",
        orderNumber: "ORD-2026-002",
        customerName: "Tech Startup JSC",
        serviceName: "Business License",
        ratecard: 7_000_000,
        ctvPrice: 8_800_000,
        commission: 1_800_000,
      },
      {
        orderId: "o7",
        orderNumber: "ORD-2026-007",
        customerName: "XYZ Ltd",
        serviceName: "Work Permit",
        ratecard: 4_000_000,
        ctvPrice: 5_000_000,
        commission: 1_000_000,
      },
    ],
  },
  {
    id: "ctv2",
    name: "Linh Partner",
    phone: "0909333444",
    email: "linh.partner@mail.com",
    status: "active",
    totalJobs: 1,
    totalCommission: 500_000,
    jobs: [
      {
        orderId: "o5",
        orderNumber: "ORD-2026-005",
        customerName: "ABC Corp",
        serviceName: "Visa Processing",
        ratecard: 2_500_000,
        ctvPrice: 3_000_000,
        commission: 500_000,
      },
    ],
  },
  {
    id: "ctv3",
    name: "Minh Agency",
    phone: "0909555666",
    email: "minh.agency@mail.com",
    status: "active",
    totalJobs: 3,
    totalCommission: 1_200_000,
    jobs: [],
  },
  {
    id: "ctv4",
    name: "An Consultant",
    phone: "0911222333",
    email: "an.consultant@mail.com",
    status: "inactive",
    totalJobs: 0,
    totalCommission: 0,
    jobs: [],
  },
  {
    id: "ctv5",
    name: "Bao Network",
    phone: "0911444555",
    email: "bao.network@mail.com",
    status: "active",
    totalJobs: 5,
    totalCommission: 4_500_000,
    jobs: [],
  },
  {
    id: "ctv6",
    name: "Chi Freelance",
    phone: "0911666777",
    email: "chi.freelance@mail.com",
    status: "active",
    totalJobs: 1,
    totalCommission: 350_000,
    jobs: [],
  },
  {
    id: "ctv7",
    name: "Dung Partner",
    phone: "0911888999",
    email: "dung.partner@mail.com",
    status: "inactive",
    totalJobs: 2,
    totalCommission: 800_000,
    jobs: [],
  },
  {
    id: "ctv8",
    name: "Em CTV",
    phone: "0922111222",
    email: "em.ctv@mail.com",
    status: "active",
    totalJobs: 4,
    totalCommission: 2_100_000,
    jobs: [],
  },
  {
    id: "ctv9",
    name: "Phong Broker",
    phone: "0922333444",
    email: "phong.broker@mail.com",
    status: "active",
    totalJobs: 0,
    totalCommission: 0,
    jobs: [],
  },
  {
    id: "ctv10",
    name: "Quynh Sales",
    phone: "0922555666",
    email: "quynh.sales@mail.com",
    status: "active",
    totalJobs: 6,
    totalCommission: 5_200_000,
    jobs: [],
  },
  {
    id: "ctv11",
    name: "Son Field",
    phone: "0922777888",
    email: "son.field@mail.com",
    status: "inactive",
    totalJobs: 1,
    totalCommission: 200_000,
    jobs: [],
  },
  {
    id: "ctv12",
    name: "Trang Partner",
    phone: "0922999000",
    email: "trang.partner@mail.com",
    status: "active",
    totalJobs: 2,
    totalCommission: 950_000,
    jobs: [],
  },
];
